# This is a generated file. Not intended for manual editing.
services:
  foody.presentationlayer:
    build:
      context: "/Users/gamzeatik/RiderProjects/Foody"
      dockerfile: "Foody.PresentationLayer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/Foody.PresentationLayer.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net6.0/Foody.PresentationLayer.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "foody.presentationlayer:dev"
    ports: []
    volumes:
    - "/Users/gamzeatik/.nuget/packages:/root/.nuget/packages"
    - "/Users/gamzeatik/RiderProjects/Foody/Foody.PresentationLayer:/app:rw"
    - "/Users/gamzeatik/RiderProjects/Foody:/src:rw"
    working_dir: "/app"
